export const images = {
  logo: require('../images/logo.png'),
  book1: require('../images/book1.png'),
  book2: require('../images/book2.png'),
  book3: require('../images/book3.png'),
  book4: require('../images/book4.png'),
  check: require('../images/check.png'),
  google: require('../images/google.png'),
  apple: require('../images/apple.png'),
  logout: require('../images/logout.png'),
  facebook: require('../images/facebook.png'),
  visa: require('../images/visa.png'),
  gift: require('../images/gift.png'),

  rider: require('../images/rider.png'),
  rider_user: require('../images/rider_user.png'),
  map_rider: require('../images/map_rider.png'),
  congrat: require('../images/congrat.png'),
  meezan_bank: require('../images/meezan_bank.png'),
  visa_card: require('../images/visa_card.png'),
  books_sale: require('../images/books_sale.jpeg'),
  add_unfill: require('../icons/add_unfill.png'),
  check_box: require('../icons/check_box.png'),
  tick: require('../icons/tick.png'),
  plus: require('../icons/plus.png'),
  down_arrow: require('../icons/down_arrow.png'),
  location_center: require('../icons/location_center.png'),
  search: require('../icons/search.png'),
  bell: require('../icons/bell.png'),
  close: require('../icons/close.png'),
  eye: require('../icons/eye.png'),
  drawer: require('../icons/drawer.png'),
  fill_add: require('../icons/fill_add.png'),
  fill_box: require('../icons/fill_box.png'),
  fill_cart: require('../icons/fill_cart.png'),
  fill_heart: require('../icons/fill_heart.png'),
  fill_home: require('../icons/fill_home.png'),
  filter: require('../icons/filter.png'),
  unfill_box: require('../icons/unfill_box.png'),
  unfill_cart : require('../icons/unfill_cart.png'),
  unfill_heart: require('../icons/unfill_heart.png'),
  unfill_home: require('../icons/unfill_home.png'),
  right_arrow: require('../icons/right_arrow.png'),
  left_arrow: require('../icons/left_arrow.png'),
  like: require('../icons/like.png'),
  fill_star: require('../icons/fill_star.png'),
  unfill_star: require('../icons/unfill_star.png'),
  edit: require('../icons/edit.png'),
  share: require('../icons/share.png'),
  dots: require('../icons/dots.png'),
  copy: require('../icons/copy.png'),

  call: require('../icons/call.png'),

};
